name: Trigger auto deployment for container-app-h3uq7cymypxfw

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-h3uq7cymypxfw-AutoDeployTrigger-87040ed8-39e2-4e97-a261-74449325c1da.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPH3UQ7CYMYPXFW_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPH3UQ7CYMYPXFW_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPH3UQ7CYMYPXFW_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryh3uq7cymypxfw.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPH3UQ7CYMYPXFW_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPH3UQ7CYMYPXFW_REGISTRY_PASSWORD }}
          containerAppName: container-app-h3uq7cymypxfw
          resourceGroup: expresssample8eba9101
          imageToBuild: containerregistryh3uq7cymypxfw.azurecr.io/container-app-h3uq7cymypxfw:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


